/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";
import useWindowSize from "../hook/useWindowSize";

const MODEL_SRC = "./models/WawaOffice.glb";

const WorkspaceModel = (props) => {
  const { nodes, materials } = useGLTF(MODEL_SRC);
  const ref = useRef();

  // useFrame((_, delta) => (ref.current.rotation.y += delta));

  return (
    <mesh
      {...props}
      ref={ref}
      geometry={nodes["01_office"].geometry}
      material={materials["01"]}
    />
  );
};

export default WorkspaceModel;

useGLTF.preload("./models/WawaOffice.glb");
